function getEditorRepeatMinutes(){const v=$("#repeatSelect").value;if(v!=="custom")return Number(v)||0;const n=Math.max(1,Number($("#repeatCustomValue").value)||1);return $("#repeatCustomUnit").value==="hour"?n*60:n;}
function savePlanEdit(){
  const t=currentPlanTask();if(!t)return;
  const newText=$("#planTextInput").value.trim();let newDate=$("#planDateInput").value||null;let newTime=$("#planTimeInput").value||null;const newRepeat=getEditorRepeatMinutes();const newRepeatDaily=newRepeat>0&&$("#repeatDailyToggle").checked;const newRepeatStart=newRepeatDaily?($("#repeatStartTimeInput").value||null):null;const newRepeatEnd=newRepeatDaily?($("#repeatEndTimeInput").value||null):null;const newEndNextDay=newRepeatDaily&&newRepeatStart&&newRepeatEnd?timeToMinutes(newRepeatEnd)<=timeToMinutes(newRepeatStart):false;const preserveOnceWindow=!newRepeatDaily&&newRepeat>0&&!!t.repeatWindowStartAt&&!!t.repeatWindowEndAt;
  if(!newText){toast("事情内容不能为空");return;}if(newRepeatDaily&&(!newRepeatStart||!newRepeatEnd)){toast("请设置每天的开始和结束时间");return;}
  if(newRepeatDaily){const target=nextDailyWindowOccurrence(newRepeatStart,newRepeatEnd,newRepeat,new Date(Date.now()-1000),newEndNextDay);if(target){newDate=localDate(target);newTime=`${String(target.getHours()).padStart(2,"0")}:${String(target.getMinutes()).padStart(2,"0")}`;}}
  else if(preserveOnceWindow){const target=nextOneTimeWindowOccurrence(t.repeatWindowStartAt,t.repeatWindowEndAt,newRepeat,new Date(Date.now()-1000));if(target){newDate=localDate(target);newTime=`${String(target.getHours()).padStart(2,"0")}:${String(target.getMinutes()).padStart(2,"0")}`;}else{newDate=localDate(new Date(t.repeatWindowStartAt));newTime=null;}}
  else if(newRepeat>0&&(!newDate||!newTime)){const target=new Date(Date.now()+newRepeat*60000);newDate=localDate(target);newTime=`${String(target.getHours()).padStart(2,"0")}:${String(target.getMinutes()).padStart(2,"0")}`;}
  if(newTime&&!newDate&&currentPlanOrigin==="today")newDate=localDate();if(newTime&&!newDate){toast("先选日期，再设时间");return;}
  const before=taskSnapshot(t),changes=[];if(t.text!==newText)changes.push(`text:${t.text} -> ${newText}`);if((t.plannedDate||null)!==newDate)changes.push(`date:${t.plannedDate||""} -> ${newDate||""}`);if((t.plannedTime||null)!==newTime)changes.push(`time:${t.plannedTime||""} -> ${newTime||""}`);if((Number(t.repeatMinutes)||0)!==newRepeat)changes.push(`repeat:${Number(t.repeatMinutes)||0} -> ${newRepeat}`);if(!!t.repeatDaily!==newRepeatDaily)changes.push(`repeat_daily:${!!t.repeatDaily} -> ${newRepeatDaily}`);
  const keepAnchor=t.anchor&&(!newDate||newDate===localDate());t.text=newText;t.rawText=newText;t.plannedDate=newDate;t.plannedTime=newTime;t.repeatMinutes=newRepeat;t.repeatLabel=newRepeat?repeatText(newRepeat).replace(/\s/g,""):"";t.repeatDaily=newRepeatDaily;t.repeatStartTime=newRepeatStart;t.repeatEndTime=newRepeatEnd;t.repeatEndNextDay=newEndNextDay;
  if(newRepeatDaily){t.repeatWindowStartAt=null;t.repeatWindowEndAt=null;t.repeatWindowEnded=false;}else if(!preserveOnceWindow){t.repeatWindowStartAt=null;t.repeatWindowEndAt=null;t.repeatWindowEnded=false;}else{t.repeatWindowEnded=!newTime;}t.anchor=keepAnchor;
  if(newRepeatDaily||preserveOnceWindow)t.bucket="today";else if(newDate)t.bucket=newDate===localDate()?"today":"later";else{t.bucket=currentPlanOrigin==="today"?"today":"later";if(t.bucket==="later"&&!t.laterOrder)t.laterOrder=nextLaterOrder();}if(t.bucket!=="today")t.anchor=false;
  syncDueAt(t);resetReminderFlags(t);logEvent(t,"task_edited",{detail:changes.join(" | ")});saveState();hideSheet("planSheet");render();if(manageMode==="organize")renderOrganizer();if(changes.length)toast("已保存","撤销",()=>{restoreSnapshot(t,before);logEvent(t,"undo_edit");saveState();render();if(manageMode==="organize")renderOrganizer();});else toast("没有变化");
}
function movePlanToday(){const t=currentPlanTask();if(!t)return;const before=taskSnapshot(t),editedText=$("#planTextInput").value.trim();if(editedText)t.text=editedText;t.plannedDate=localDate();t.plannedTime=$("#planTimeInput").value||t.plannedTime||null;t.bucket="today";t.anchor=false;syncDueAt(t);resetReminderFlags(t);logEvent(t,"moved_today");saveState();hideSheet("planSheet");render();renderOrganizer();toast("已移到今天","撤销",()=>{restoreSnapshot(t,before);logEvent(t,"undo_move_today");saveState();render();renderOrganizer();});}
function clearPlanTime(){const t=currentPlanTask();if(!t)return;if(Number(t.repeatMinutes)>0){toast("请先把循环改为“不循环”");return;}if(!t.plannedTime&&!$("#planTimeInput").value){toast("当前没有时间");return;}const before=taskSnapshot(t);t.plannedTime=null;t.dueAt=null;resetReminderFlags(t);logEvent(t,"time_cleared");saveState();$("#planTimeInput").value="";hideSheet("planSheet");render();renderOrganizer();toast("已清除时间","撤销",()=>{restoreSnapshot(t,before);logEvent(t,"undo_time_clear");saveState();render();renderOrganizer();});}
function clearPlanDate(){const t=currentPlanTask();if(!t)return;if(Number(t.repeatMinutes)>0){toast("请先把循环改为“不循环”");return;}const before=taskSnapshot(t);t.plannedDate=null;t.plannedTime=null;t.dueAt=null;t.bucket="later";t.anchor=false;resetReminderFlags(t);t.laterOrder=nextLaterOrder();logEvent(t,"date_cleared");saveState();$("#planDateInput").value="";$("#planTimeInput").value="";hideSheet("planSheet");render();renderOrganizer();toast("已取消日期","撤销",()=>{restoreSnapshot(t,before);logEvent(t,"undo_date_clear");saveState();render();renderOrganizer();});}
function abandonPlan(){const t=currentPlanTask();if(!t)return;markRemoved(t,"from_later_organize");}
let undoHandler=null;
function toast(msg,actionLabel=null,actionFn=null){const t=$("#toast"),text=$("#toastText"),btn=$("#toastAction");if(!t||!text||!btn)return;text.textContent=msg;btn.classList.toggle("hidden",!actionLabel);btn.textContent=actionLabel||"";undoHandler=actionFn||null;btn.onclick=()=>{const fn=undoHandler;undoHandler=null;t.classList.remove("show");if(fn)fn();};t.classList.add("show");clearTimeout(t._timer);t._timer=setTimeout(()=>{t.classList.remove("show");undoHandler=null;},actionLabel?7000:1700);}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));}
function exportCSV(){const cols=["event_time","task_id","task_text","action","planned_date","planned_time","repeat_minutes","repeat_daily","repeat_start_time","repeat_end_time","created_at","completed_at","anchor","bucket","carry_count","detail"],rows=[cols.join(",")];for(const e of state.events)rows.push(cols.map(k=>csvCell(e[k]??"")).join(","));const blob=new Blob(["\ufeff"+rows.join("\n")],{type:"text/csv;charset=utf-8"});const url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`做点儿啥-行为记录-${localDate()}.csv`;a.click();URL.revokeObjectURL(url);toast("已导出");}
function csvCell(v){const s=String(v).replace(/"/g,'""');return `"${s}"`;}
async function unlockAudio(){try{if(!audioCtx){const AC=window.AudioContext||window.webkitAudioContext;if(AC)audioCtx=new AC();}if(audioCtx&&audioCtx.state==="suspended")await audioCtx.resume();}catch(e){}}
function tone(freq,start,duration,gain=0.035){if(!audioCtx||audioCtx.state!=="running")return;const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type="sine";o.frequency.value=freq;g.gain.setValueAtTime(0.0001,audioCtx.currentTime+start);g.gain.exponentialRampToValueAtTime(gain,audioCtx.currentTime+start+0.015);g.gain.exponentialRampToValueAtTime(0.0001,audioCtx.currentTime+start+duration);o.connect(g);g.connect(audioCtx.destination);o.start(audioCtx.currentTime+start);o.stop(audioCtx.currentTime+start+duration+0.02);}
function playCue(kind="lead"){unlockAudio();if(!audioCtx||audioCtx.state!=="running")return;if(kind==="due"){tone(720,0,.15,.085);tone(900,.19,.17,.075);}else if(kind==="repeat"){tone(700,0,.13,.07);tone(820,.16,.13,.06);}else if(kind==="review")tone(610,0,.17,.055);else tone(680,0,.17,.065);}
async function enableNotifications(){unlockAudio();if(!("Notification" in window)){toast("当前浏览器不支持通知");return;}const p=await Notification.requestPermission();notificationNudgeVisible=false;toast(p==="granted"?"提醒已开启":"未获得通知权限");updateNotifyBtn();renderInputNotices();}
function updateNotifyBtn(){const btn=$("#notifyBtn"),status=$("#notifyStatus");if(!("Notification" in window)){btn.textContent="不支持";btn.disabled=true;status.textContent="当前浏览器不支持";}else{btn.disabled=Notification.permission!=="default";btn.textContent=Notification.permission==="granted"?"已开启":Notification.permission==="denied"?"未开启":"开启";status.textContent=Notification.permission==="granted"?"已开启":"未开启";}}
function notify(title,body,{kind="lead",requireInteraction=false,onClick=null}={}){playCue(kind);if(!("Notification" in window)||Notification.permission!=="granted"){toast(`${title} · ${body}`);return null;}try{const n=new Notification(title,{body,icon:"icons/icon-192.png",requireInteraction});if(onClick)n.onclick=()=>{try{window.focus()}catch(e){}onClick();n.close();};return n;}catch(e){toast(`${title} · ${body}`);return null;}}
function checkTaskReminders(){const lead=+state.settings.leadMinutes;let changed=false;for(const t of state.tasks){if(t.status!=="active"||t.repeatWindowEnded)continue;const due=dueDateForTask(t);if(!due)continue;const diff=(due.getTime()-Date.now())/60000;if(Number(t.repeatMinutes)>0){if(diff<=0){notify(repeatText(t.repeatMinutes),t.text,{kind:"repeat",requireInteraction:true});t.lastRepeatReminderAt=nowISO();logEvent(t,"repeat_reminder_shown");advanceRepeatToFuture(t,due);changed=true;}continue;}if(!isTodayTask(t))continue;if(diff<=lead&&diff>0&&!t.leadSent){const n=Math.max(1,Math.ceil(diff));notify(`还有 ${n} 分钟`,t.text,{kind:"lead"});t.leadSent=true;logEvent(t,"lead_reminder_shown",{detail:`${n}m`});changed=true;}if(diff<=0&&diff>=-10&&!t.dueSent){notify(t.plannedTime||"现在",t.text,{kind:"due",requireInteraction:true});t.dueSent=true;logEvent(t,"due_reminder_shown");changed=true;}}if(changed){saveState();render();}}
function checkReviewNotification(){const now=new Date(),today=localDate(now);if(!state.settings.eveningReview||now.getHours()<REVIEW_HOUR)return;const unfinished=activeToday().filter(t=>!Number(t.repeatMinutes));if(!unfinished.length||state.meta.reviewNotifiedDate===today)return;notify("今天要收个尾吗？",`还有 ${unfinished.length} 件事`,{kind:"review",onClick:()=>{renderReview(activeToday().filter(t=>!Number(t.repeatMinutes)));setManageMode("review");}});state.meta.reviewNotifiedDate=today;logEvent(null,"evening_review_reminder_shown",{detail:String(unfinished.length)});saveState();}
function clockTick(){cleanupRecycle();const today=localDate();if(today!==lastUiDay){lastUiDay=today;state.tasks.forEach(t=>{if(t.plannedDate===today){t.leadSent=false;t.dueSent=false;}});saveState();render();}else{fmtDateLabel();renderNext();renderPrompts();}checkTaskReminders();checkReviewNotification();}
