function handleTaskListClick(e){const complete=e.target.closest("[data-complete]");if(complete){completeTask(complete.dataset.complete);return;}const pin=e.target.closest("[data-pin]");if(pin){toggleAnchor(pin.dataset.pin);return;}const more=e.target.closest("[data-task-menu]");if(more){const r=more.getBoundingClientRect();openTaskMenu(more.dataset.taskMenu,r.right,r.bottom+4);return;}const edit=e.target.closest("[data-edit]");if(edit){openPlan(edit.dataset.edit);return;}}
function openTaskMenu(id,x,y){taskMenuTaskId=id;const menu=$("#taskMenu");menu.style.left=`${x}px`;menu.style.top=`${y}px`;menu.classList.add("show");requestAnimationFrame(()=>{const r=menu.getBoundingClientRect();if(r.right>innerWidth-8)menu.style.left=`${Math.max(8,innerWidth-r.width-8)}px`;if(r.bottom>innerHeight-8)menu.style.top=`${Math.max(8,y-r.height-8)}px`;});}
function hideTaskMenu(){$("#taskMenu").classList.remove("show");taskMenuTaskId=null;}
function handleTaskContextMenu(e){const task=e.target.closest(".task");if(!task)return;e.preventDefault();openTaskMenu(task.dataset.id,e.clientX,e.clientY);}
["todayList","laterList","glanceAnchorList"].forEach(id=>{$("#"+id).addEventListener("click",handleTaskListClick);$("#"+id).addEventListener("contextmenu",handleTaskContextMenu);});
$("#addBtn").onclick=addTask;$("#taskInput").addEventListener("keydown",e=>{if(e.key==="Enter")addTask()});$$(".tab").forEach(b=>b.onclick=()=>{activeTab=b.dataset.tab;uiState.activeTab=activeTab;saveUiState();render();});
$("#expandBtn").onclick=()=>setExpanded(!uiState.expanded);$("#moreBtn").onclick=e=>{e.stopPropagation();const menu=$("#appMenu"),show=!menu.classList.contains("show");menu.classList.toggle("show",show);$("#moreBtn").setAttribute("aria-expanded",show?"true":"false");};
$('[data-app-mode="settings"]').onclick=()=>setManageMode("settings");$('[data-app-mode="recentRemoved"]').onclick=()=>setManageMode("recentRemoved");$("#manageBackBtn").onclick=()=>setManageMode("main");
$$('[data-close]').forEach(b=>b.onclick=()=>hideSheet(b.dataset.close));$$(".sheet-backdrop").forEach(x=>x.addEventListener("click",e=>{if(e.target===x)x.classList.remove("show")}));
$("#openReviewBtn").onclick=()=>{renderReview(activeToday().filter(t=>!Number(t.repeatMinutes)));setManageMode("review");};$("#openStaleBtn").onclick=()=>{renderReview(staleTasks(),"之前留下的事情");setManageMode("review");};$("#organizeBtn").onclick=()=>setManageMode("organize");
$("#repeatSelect").onchange=()=>{$("#repeatCustom").classList.toggle("hidden",$("#repeatSelect").value!=="custom");if($("#repeatSelect").value==="0"){$("#repeatDailyToggle").checked=false;$("#repeatWindowFields").classList.add("hidden");}};
$("#repeatDailyToggle").onchange=()=>{if($("#repeatDailyToggle").checked&&$("#repeatSelect").value==="0"){$("#repeatDailyToggle").checked=false;toast("请先选择循环间隔");return;}$("#repeatWindowFields").classList.toggle("hidden",!$("#repeatDailyToggle").checked);};
$("#completedToggle").addEventListener("click",()=>{completedExpanded=!completedExpanded;renderCompleted();});$("#recentCompletedBtn").addEventListener("click",()=>setManageMode("recentCompleted"));$("#savePlanBtn").onclick=savePlanEdit;$("#planAbandonBtn").onclick=abandonPlan;
$("#manualTimeBtn").onclick=()=>{const id=lastParseIssueTaskId;lastParseIssueTaskId=null;renderInputNotices();if(id)openPlan(id);};$("#inlineNotifyBtn").onclick=enableNotifications;
$("#taskMenuEdit").onclick=()=>{const id=taskMenuTaskId;hideTaskMenu();if(id)openPlan(id);};$("#taskMenuAbandon").onclick=()=>{const t=state.tasks.find(x=>x.id===taskMenuTaskId);hideTaskMenu();if(t)markRemoved(t,"task_menu");};
$("#leadSelect").value=state.settings.leadMinutes;$("#reviewToggle").checked=state.settings.eveningReview;$("#leadSelect").onchange=e=>{state.settings.leadMinutes=+e.target.value;saveState();};$("#reviewToggle").onchange=e=>{state.settings.eveningReview=e.target.checked;saveState();render();};
$("#exportBtn").onclick=()=>{exportCSV();$("#appMenu").classList.remove("show");$("#moreBtn").setAttribute("aria-expanded","false");};$("#notifyBtn").onclick=enableNotifications;$("#testSoundBtn").onclick=async()=>{await unlockAudio();playCue("due");toast(audioCtx&&audioCtx.state==="running"?"已播放测试提示音":"浏览器暂未允许网页播放声音");};
$("#clearBtn").onclick=()=>setManageMode("clear");$("#cancelClearBtn").onclick=()=>setManageMode("settings");$("#confirmClearBtn").onclick=()=>{state=defaultState();saveState();manageMode="main";lastParseIssueTaskId=null;notificationNudgeVisible=false;render();toast("已清空");};
document.addEventListener("click",e=>{if(!e.target.closest("#appMenu")&&!e.target.closest("#moreBtn")){$("#appMenu").classList.remove("show");$("#moreBtn").setAttribute("aria-expanded","false");}if(!e.target.closest("#taskMenu")&&!e.target.closest("[data-task-menu]"))hideTaskMenu();});document.addEventListener("pointerdown",unlockAudio,{once:true});document.addEventListener("keydown",unlockAudio,{once:true});
function applyThemeColor(){const systemDark=window.matchMedia&&window.matchMedia("(prefers-color-scheme: dark)").matches;const dark=uiState.theme==="dark"||(uiState.theme==="system"&&systemDark);const meta=document.querySelector('meta[name="theme-color"]');if(meta)meta.setAttribute("content",dark?"#1f211e":"#f2efe7");}
function applyThemePreference(){if(uiState.theme==="system")document.documentElement.removeAttribute("data-theme");else document.documentElement.setAttribute("data-theme",uiState.theme);$("#themeSelect").value=uiState.theme;applyThemeColor();}
$("#themeSelect").onchange=e=>{uiState.theme=e.target.value;saveUiState();applyThemePreference();};applyThemePreference();if(window.matchMedia){const mq=window.matchMedia("(prefers-color-scheme: dark)");if(mq.addEventListener)mq.addEventListener("change",()=>{if(uiState.theme==="system")applyThemeColor();});}
updateNotifyBtn();render();checkTaskReminders();checkReviewNotification();setInterval(clockTick,5000);if("serviceWorker" in navigator){window.addEventListener("load",()=>navigator.serviceWorker.register("./sw.js").catch(()=>{}));}
