[package]
name = "dostuff_windows"
version = "2.7.1"
description = "Windows shell for Do Stuff"
authors = ["Ann"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-ico"] }

[[bin]]
name = "DoStuff"
path = "src/main.rs"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.59", features = ["Win32_Foundation", "Win32_UI_WindowsAndMessaging"] }
